# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers
[[headers]]
  # Define custom headers for all files
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
